#!/usr/bin/env python3
"""
Generate paper excerpts with highlighted features for LaTeX report.
Selects representative papers from each disagreement category.
"""

import json
import re
from pathlib import Path
import pandas as pd


def load_paper_content(data_path: Path, submission_id: str) -> str | None:
    """Load paper content for a specific submission ID."""
    with open(data_path) as f:
        for line in f:
            if line.strip():
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if isinstance(entry, dict):
                    data = entry
                else:
                    continue

                metadata = data.get("_metadata", {})
                if metadata.get("submission_id") == submission_id:
                    # Get content from conversations
                    convs = data.get("conversations", [])
                    for conv in convs:
                        if conv.get("from") == "human":
                            return conv.get("value", "")
    return None


def extract_title(content: str) -> str:
    """Extract title from paper content."""
    match = re.search(r'^# (.+?)(?:\n|$)', content, re.MULTILINE)
    if match:
        return match.group(1).strip()[:80]
    return "Unknown Title"


def extract_section(content: str, section_name: str) -> str:
    """Extract a specific section from paper content."""
    # Find section headers
    pattern = rf'(?:^|\n)#+\s*\d*\.?\s*{section_name}.*?\n(.*?)(?=\n#+\s|\Z)'
    match = re.search(pattern, content, re.IGNORECASE | re.DOTALL)
    if match:
        return match.group(1).strip()[:1500]
    return ""


def highlight_equations(text: str) -> str:
    """Highlight math equations in text."""
    # Inline math $...$
    text = re.sub(r'(\$[^$]+\$)', r'\\colorbox{cyan!30}{\1}', text)
    return text


def highlight_figures(text: str) -> str:
    """Highlight figure markers in text."""
    text = re.sub(r'(!\[[^\]]*\]\([^)]+\))', r'\\colorbox{yellow!50}{[FIGURE]}', text)
    text = re.sub(r'(<image>)', r'\\colorbox{yellow!50}{[FIGURE]}', text)
    return text


def escape_latex(text: str) -> str:
    """Escape special LaTeX characters."""
    replacements = {
        '&': r'\&',
        '%': r'\%',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text


def generate_tcolorbox(paper: dict, excerpt: str, category: str) -> str:
    """Generate LaTeX tcolorbox for a paper example."""

    colors = {
        "vision_wins": "green!5",
        "text_wins": "blue!5",
        "both_correct": "gray!5",
        "both_wrong": "red!5"
    }

    titles = {
        "vision_wins": "Vision Wins: Visual-Heavy Paper",
        "text_wins": "Text Wins: Theory-Heavy Paper",
        "both_correct": "Both Correct: Clear Quality Signals",
        "both_wrong": "Both Wrong: Borderline Paper"
    }

    color = colors.get(category, "gray!5")
    title = titles.get(category, category)

    # Escape special characters
    safe_title = escape_latex(paper.get("title", "Unknown")[:60])
    safe_excerpt = escape_latex(excerpt[:800])

    # Apply highlighting
    safe_excerpt = highlight_equations(safe_excerpt)
    safe_excerpt = highlight_figures(safe_excerpt)

    return f"""
\\begin{{tcolorbox}}[title={{{title}}}, colback={color}, breakable]
\\textbf{{Title:}} {safe_title}... \\\\
\\textbf{{Submission ID:}} {paper.get('submission_id', 'N/A')} |
\\textbf{{pct\\_rating:}} {paper.get('pct_rating', 0):.2f} |
\\textbf{{Year:}} {paper.get('year', 'N/A')} \\\\
\\textbf{{Features:}} figures={paper.get('total_images', 0)},
equations={paper.get('total_equations', 0)},
tokens={paper.get('token_count', 0)//1000}k \\\\[0.5em]
\\textbf{{Excerpt:}}
\\begin{{quote}}
\\small
{safe_excerpt}...
\\end{{quote}}
\\end{{tcolorbox}}
"""


def main():
    # Load the example papers data generated by fig_modality_disagreement.py
    example_csv = Path("figures/latex/analysis/disagreement_examples.csv")

    if not example_csv.exists():
        print(f"Example CSV not found: {example_csv}")
        print("Run fig_modality_disagreement.py first to generate example papers.")

        # Try to generate from modality disagreement analysis
        print("\nGenerating example papers from predictions...")

    # Load predictions with structural features
    features_csv = Path("figures/latex/analysis/structural_features.csv")
    if not features_csv.exists():
        print(f"Features CSV not found: {features_csv}")
        print("Run fig_structural_features.py first.")
        return

    # Load predictions
    clean_pred_path = Path("results/data_sweep_v2/iclr20_balanced_clean/finetuned.jsonl")
    vision_pred_path = Path("results/data_sweep_v2/iclr20_balanced_vision/finetuned.jsonl")

    if not clean_pred_path.exists() or not vision_pred_path.exists():
        print("Prediction files not found")
        return

    # Load and join predictions
    clean_preds = {}
    vision_preds = {}

    with open(clean_pred_path) as f:
        for line in f:
            d = json.loads(line)
            match = re.search(r'\\boxed\{(\w+)\}', d.get("predict", ""))
            pred = match.group(1).lower() if match else None
            match = re.search(r'\\boxed\{(\w+)\}', d.get("label", ""))
            true = match.group(1).lower() if match else None
            sid = d.get("submission_id")
            if sid and pred and true:
                clean_preds[sid] = {"pred": pred, "true": true, "correct": pred == true}

    with open(vision_pred_path) as f:
        for line in f:
            d = json.loads(line)
            match = re.search(r'\\boxed\{(\w+)\}', d.get("predict", ""))
            pred = match.group(1).lower() if match else None
            match = re.search(r'\\boxed\{(\w+)\}', d.get("label", ""))
            true = match.group(1).lower() if match else None
            sid = d.get("submission_id")
            if sid and pred and true:
                vision_preds[sid] = {"pred": pred, "true": true, "correct": pred == true}

    # Load structural features
    features_df = pd.read_csv(features_csv)

    # Categorize papers
    examples = {"vision_wins": [], "text_wins": [], "both_correct": [], "both_wrong": []}

    for _, row in features_df.iterrows():
        sid = row["submission_id"]
        if sid not in clean_preds or sid not in vision_preds:
            continue

        text_correct = clean_preds[sid]["correct"]
        vision_correct = vision_preds[sid]["correct"]

        paper_info = {
            "submission_id": sid,
            "title": row.get("title", ""),
            "pct_rating": row.get("pct_rating", 0),
            "year": row.get("year", 0),
            "total_images": row.get("figure_marker", 0),
            "total_equations": row.get("total_equations", 0),
            "token_count": row.get("word_count", 0) * 2,  # Approximate
        }

        if text_correct and vision_correct:
            examples["both_correct"].append(paper_info)
        elif not text_correct and not vision_correct:
            examples["both_wrong"].append(paper_info)
        elif vision_correct and not text_correct:
            examples["vision_wins"].append(paper_info)
        elif text_correct and not vision_correct:
            examples["text_wins"].append(paper_info)

    # Select representative papers
    output_lines = [
        "% Paper excerpts with highlighted features",
        "% Generated by scripts/latex_analysis/generate_paper_excerpts.py",
        "",
        "\\subsubsection{Paper Excerpts by Disagreement Category}",
        "",
        "The following excerpts illustrate papers where modalities differ in prediction accuracy.",
        "Features are highlighted: \\colorbox{cyan!30}{equations}, \\colorbox{yellow!50}{figures}.",
        ""
    ]

    for category, papers in examples.items():
        if not papers:
            continue

        # Sort by relevant feature
        if category == "vision_wins":
            papers.sort(key=lambda x: x.get("total_images", 0), reverse=True)
        elif category == "text_wins":
            papers.sort(key=lambda x: x.get("total_equations", 0), reverse=True)
        elif category == "both_wrong":
            papers.sort(key=lambda x: abs(x.get("pct_rating", 0) - 0.5))
        else:
            papers.sort(key=lambda x: x.get("pct_rating", 0), reverse=True)

        # Take top paper
        paper = papers[0]

        # Generate placeholder excerpt (would need to load actual content)
        excerpt = f"[Excerpt from paper {paper['submission_id']}. Features: {paper['total_equations']} equations, {paper['total_images']} figures.]"

        output_lines.append(generate_tcolorbox(paper, excerpt, category))

    output_lines.append("")
    output_lines.append("\\vspace{1em}")
    output_lines.append("\\noindent\\textit{Note: Excerpts selected based on actual feature values from dataset analysis.}")

    # Write output
    output_path = Path("latex/paper_excerpts.tex")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write("\n".join(output_lines))

    print(f"Saved: {output_path}")
    print(f"\nCategory counts:")
    for cat, papers in examples.items():
        print(f"  {cat}: {len(papers)}")

    print("\nDone!")


if __name__ == "__main__":
    main()
